// RevenueCat seed script for SiteTrack
// Run: pnpm --filter @workspace/scripts exec tsx src/seedRevenueCat.ts
//
// Requires revenueCatClient.ts in this directory (generated by RevenueCat integration).
// Run AFTER completing the RevenueCat integration setup in Replit.

import { getUncachableRevenueCatClient } from "./revenueCatClient";
import {
  listProjects,
  createProject,
  listApps,
  createApp,
  listProducts,
  createProduct,
  listEntitlements,
  createEntitlement,
  attachProductsToEntitlement,
  listOfferings,
  createOffering,
  updateOffering,
  listPackages,
  createPackages,
  attachProductsToPackage,
  listAppPublicApiKeys,
  type App,
  type Product,
  type Project,
  type Entitlement,
  type Offering,
  type Package,
  type CreateProductData,
} from "@replit/revenuecat-sdk";

const PROJECT_NAME = "SiteTrack";
const APP_STORE_APP_NAME = "SiteTrack iOS";
const APP_STORE_BUNDLE_ID = "com.butaddei.sitetrack";
const PLAY_STORE_APP_NAME = "SiteTrack Android";
const PLAY_STORE_PACKAGE_NAME = "com.butaddei.sitetrack";

// ─── Products ─────────────────────────────────────────────────────────────────
const PRODUCTS = [
  {
    identifier: "com.sitetrack.basic.monthly",
    playStoreIdentifier: "com.sitetrack.basic.monthly:monthly",
    displayName: "SiteTrack Basic Monthly",
    title: "SiteTrack Basic Monthly",
    entitlement: "basic",
    packageKey: "basic_monthly",
    packageLabel: "Basic Monthly",
    prices: [
      { amount_micros: 9900000, currency: "USD" },  // $9.90
      { amount_micros: 8900000, currency: "EUR" },  // €8.90
    ],
  },
  {
    identifier: "com.sitetrack.pro.monthly",
    playStoreIdentifier: "com.sitetrack.pro.monthly:monthly",
    displayName: "SiteTrack Pro Monthly",
    title: "SiteTrack Pro Monthly",
    entitlement: "pro",
    packageKey: "pro_monthly",
    packageLabel: "Pro Monthly",
    prices: [
      { amount_micros: 19900000, currency: "USD" },  // $19.90
      { amount_micros: 17900000, currency: "EUR" },  // €17.90
    ],
  },
  {
    identifier: "com.sitetrack.business.monthly",
    playStoreIdentifier: "com.sitetrack.business.monthly:monthly",
    displayName: "SiteTrack Business Monthly",
    title: "SiteTrack Business Monthly",
    entitlement: "business",
    packageKey: "business_monthly",
    packageLabel: "Business Monthly",
    prices: [
      { amount_micros: 59900000, currency: "USD" },  // $59.90
      { amount_micros: 54900000, currency: "EUR" },  // €54.90
    ],
  },
] as const;

type TestStorePricesResponse = {
  object: string;
  prices: { amount_micros: number; currency: string }[];
};

async function seedRevenueCat() {
  const client = await getUncachableRevenueCatClient();

  // ── Project ──────────────────────────────────────────────────────────────────
  let project: Project;
  const { data: existingProjects, error: listProjectsError } = await listProjects({
    client,
    query: { limit: 20 },
  });
  if (listProjectsError) throw new Error("Failed to list projects");

  const existingProject = existingProjects.items?.find((p) => p.name === PROJECT_NAME);
  if (existingProject) {
    console.log("Project already exists:", existingProject.id);
    project = existingProject;
  } else {
    const { data: newProject, error } = await createProject({ client, body: { name: PROJECT_NAME } });
    if (error) throw new Error("Failed to create project");
    console.log("Created project:", newProject.id);
    project = newProject;
  }

  // ── Apps ─────────────────────────────────────────────────────────────────────
  const { data: apps, error: listAppsError } = await listApps({
    client,
    path: { project_id: project.id },
    query: { limit: 20 },
  });
  if (listAppsError || !apps || apps.items.length === 0) throw new Error("No apps found");

  let testApp: App | undefined = apps.items.find((a) => a.type === "test_store");
  let appStoreApp: App | undefined = apps.items.find((a) => a.type === "app_store");
  let playStoreApp: App | undefined = apps.items.find((a) => a.type === "play_store");

  if (!testApp) throw new Error("No test store app found");
  console.log("Test store app:", testApp.id);

  if (!appStoreApp) {
    const { data: newApp, error } = await createApp({
      client,
      path: { project_id: project.id },
      body: { name: APP_STORE_APP_NAME, type: "app_store", app_store: { bundle_id: APP_STORE_BUNDLE_ID } },
    });
    if (error) throw new Error("Failed to create App Store app");
    appStoreApp = newApp;
    console.log("Created App Store app:", appStoreApp.id);
  } else {
    console.log("App Store app found:", appStoreApp.id);
  }

  if (!playStoreApp) {
    const { data: newApp, error } = await createApp({
      client,
      path: { project_id: project.id },
      body: { name: PLAY_STORE_APP_NAME, type: "play_store", play_store: { package_name: PLAY_STORE_PACKAGE_NAME } },
    });
    if (error) throw new Error("Failed to create Play Store app");
    playStoreApp = newApp;
    console.log("Created Play Store app:", playStoreApp.id);
  } else {
    console.log("Play Store app found:", playStoreApp.id);
  }

  // ── Products ─────────────────────────────────────────────────────────────────
  const { data: existingProducts, error: listProductsError } = await listProducts({
    client,
    path: { project_id: project.id },
    query: { limit: 100 },
  });
  if (listProductsError) throw new Error("Failed to list products");

  const ensureProduct = async (
    targetApp: App,
    label: string,
    storeIdentifier: string,
    displayName: string,
    title: string,
    isTestStore: boolean,
  ): Promise<Product> => {
    const existing = existingProducts.items?.find(
      (p) => p.store_identifier === storeIdentifier && p.app_id === targetApp.id,
    );
    if (existing) {
      console.log(`${label} product already exists:`, existing.id);
      return existing;
    }
    const body: CreateProductData["body"] = {
      store_identifier: storeIdentifier,
      app_id: targetApp.id,
      type: "subscription",
      display_name: displayName,
    };
    if (isTestStore) {
      body.subscription = { duration: "P1M" };
      body.title = title;
    }
    const { data, error } = await createProduct({ client, path: { project_id: project.id }, body });
    if (error) throw new Error(`Failed to create ${label} product`);
    console.log(`Created ${label} product:`, data.id);
    return data;
  };

  type ProductSet = { test: Product; appStore: Product; playStore: Product };
  const productSets: ProductSet[] = [];

  for (const p of PRODUCTS) {
    const test = await ensureProduct(testApp, `Test(${p.packageKey})`, p.identifier, p.displayName, p.title, true);
    const appStore = await ensureProduct(appStoreApp, `AppStore(${p.packageKey})`, p.identifier, p.displayName, p.title, false);
    const playStore = await ensureProduct(playStoreApp, `PlayStore(${p.packageKey})`, p.playStoreIdentifier, p.displayName, p.title, false);

    // Add test store prices
    const { error: priceError } = await client.post<TestStorePricesResponse>({
      url: "/projects/{project_id}/products/{product_id}/test_store_prices",
      path: { project_id: project.id, product_id: test.id },
      body: { prices: p.prices },
    });
    if (priceError) {
      if (typeof priceError === "object" && "type" in priceError && priceError["type"] === "resource_already_exists") {
        console.log(`Test store prices already exist for ${p.packageKey}`);
      } else {
        throw new Error(`Failed to add test prices for ${p.packageKey}`);
      }
    } else {
      console.log(`Added test prices for ${p.packageKey}`);
    }

    productSets.push({ test, appStore, playStore });
  }

  // ── Entitlements ─────────────────────────────────────────────────────────────
  const { data: existingEntitlements, error: listEntitlementsError } = await listEntitlements({
    client,
    path: { project_id: project.id },
    query: { limit: 20 },
  });
  if (listEntitlementsError) throw new Error("Failed to list entitlements");

  const entitlementMap: Record<string, Entitlement> = {};

  for (let i = 0; i < PRODUCTS.length; i++) {
    const p = PRODUCTS[i];
    const { test, appStore, playStore } = productSets[i];

    let entitlement = existingEntitlements.items?.find((e) => e.lookup_key === p.entitlement);
    if (entitlement) {
      console.log(`Entitlement '${p.entitlement}' already exists:`, entitlement.id);
    } else {
      const { data, error } = await createEntitlement({
        client,
        path: { project_id: project.id },
        body: { lookup_key: p.entitlement, display_name: `${p.displayName} Access` },
      });
      if (error) throw new Error(`Failed to create entitlement '${p.entitlement}'`);
      console.log(`Created entitlement '${p.entitlement}':`, data.id);
      entitlement = data;
    }

    entitlementMap[p.entitlement] = entitlement;

    const { error: attachError } = await attachProductsToEntitlement({
      client,
      path: { project_id: project.id, entitlement_id: entitlement.id },
      body: { product_ids: [test.id, appStore.id, playStore.id] },
    });
    if (attachError) {
      if (attachError.type === "unprocessable_entity_error") {
        console.log(`Products already attached to '${p.entitlement}'`);
      } else {
        throw new Error(`Failed to attach products to entitlement '${p.entitlement}'`);
      }
    } else {
      console.log(`Attached products to entitlement '${p.entitlement}'`);
    }
  }

  // ── Offering ─────────────────────────────────────────────────────────────────
  const { data: existingOfferings, error: listOfferingsError } = await listOfferings({
    client,
    path: { project_id: project.id },
    query: { limit: 20 },
  });
  if (listOfferingsError) throw new Error("Failed to list offerings");

  let offering: Offering | undefined = existingOfferings.items?.find((o) => o.lookup_key === "default");
  if (offering) {
    console.log("Offering already exists:", offering.id);
  } else {
    const { data, error } = await createOffering({
      client,
      path: { project_id: project.id },
      body: { lookup_key: "default", display_name: "Default Offering" },
    });
    if (error) throw new Error("Failed to create offering");
    console.log("Created offering:", data.id);
    offering = data;
  }

  if (!offering.is_current) {
    const { error } = await updateOffering({
      client,
      path: { project_id: project.id, offering_id: offering.id },
      body: { is_current: true },
    });
    if (error) throw new Error("Failed to set offering as current");
    console.log("Set offering as current");
  }

  // ── Packages ─────────────────────────────────────────────────────────────────
  const { data: existingPackages, error: listPackagesError } = await listPackages({
    client,
    path: { project_id: project.id, offering_id: offering.id },
    query: { limit: 20 },
  });
  if (listPackagesError) throw new Error("Failed to list packages");

  for (let i = 0; i < PRODUCTS.length; i++) {
    const p = PRODUCTS[i];
    const { test, appStore, playStore } = productSets[i];

    let pkg: Package | undefined = existingPackages.items?.find((pk) => pk.lookup_key === p.packageKey);
    if (pkg) {
      console.log(`Package '${p.packageKey}' already exists:`, pkg.id);
    } else {
      const { data, error } = await createPackages({
        client,
        path: { project_id: project.id, offering_id: offering.id },
        body: { lookup_key: p.packageKey, display_name: p.packageLabel },
      });
      if (error) throw new Error(`Failed to create package '${p.packageKey}'`);
      console.log(`Created package '${p.packageKey}':`, data.id);
      pkg = data;
    }

    const { error: attachPkgError } = await attachProductsToPackage({
      client,
      path: { project_id: project.id, package_id: pkg.id },
      body: {
        products: [
          { product_id: test.id, eligibility_criteria: "all" },
          { product_id: appStore.id, eligibility_criteria: "all" },
          { product_id: playStore.id, eligibility_criteria: "all" },
        ],
      },
    });
    if (attachPkgError) {
      if (attachPkgError.type === "unprocessable_entity_error") {
        console.log(`Products already attached to package '${p.packageKey}'`);
      } else {
        throw new Error(`Failed to attach products to package '${p.packageKey}'`);
      }
    } else {
      console.log(`Attached products to package '${p.packageKey}'`);
    }
  }

  // ── API Keys ─────────────────────────────────────────────────────────────────
  const { data: testKeys } = await listAppPublicApiKeys({ client, path: { project_id: project.id, app_id: testApp.id } });
  const { data: iosKeys } = await listAppPublicApiKeys({ client, path: { project_id: project.id, app_id: appStoreApp.id } });
  const { data: androidKeys } = await listAppPublicApiKeys({ client, path: { project_id: project.id, app_id: playStoreApp.id } });

  console.log("\n====================");
  console.log("RevenueCat setup complete!");
  console.log("Project ID:", project.id);
  console.log("Test Store App ID:", testApp.id);
  console.log("App Store App ID:", appStoreApp.id);
  console.log("Play Store App ID:", playStoreApp.id);
  console.log("\nEntitlements: basic, pro, business");
  console.log("Packages: basic_monthly, pro_monthly, business_monthly");
  console.log("\nPublic API Keys:");
  console.log("  EXPO_PUBLIC_REVENUECAT_TEST_API_KEY =", testKeys?.items[0]?.key ?? "N/A");
  console.log("  EXPO_PUBLIC_REVENUECAT_IOS_API_KEY =", iosKeys?.items[0]?.key ?? "N/A");
  console.log("  EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY =", androidKeys?.items[0]?.key ?? "N/A");
  console.log("\nOther env vars to set:");
  console.log("  REVENUECAT_PROJECT_ID =", project.id);
  console.log("  REVENUECAT_TEST_STORE_APP_ID =", testApp.id);
  console.log("  REVENUECAT_APPLE_APP_STORE_APP_ID =", appStoreApp.id);
  console.log("  REVENUECAT_GOOGLE_PLAY_STORE_APP_ID =", playStoreApp.id);
  console.log("====================\n");
}

seedRevenueCat().catch(console.error);
